port 1194
proto udp
dev tun

ca keys/ca.crt
cert keys/sofia.crt
key keys/sofia.key
dh none
ecdh-curve secp521r1

topology subnet
mode server
tls-server

ifconfig 10.8.0.1 255.255.255.0
client-config-dir /etc/openvpn/server/clients-config
server 10.8.0.0 255.255.255.0

script-security 2
push "topology subnet"
push "route 10.100.100.0 255.255.255.0"
push "ping 15"
push "ping-restart 60"

client-to-client
keepalive 10 120
tls-auth keys/ta.key 0

management 127.0.0.1 6001

comp-lzo
user nobody
group nobody
persist-key
persist-tun
status openvpn-status.log
verb 3
