Section "Device"
    Identifier     "amdgpu"
    BusID          "PCI:7:0:0"
    Driver         "amdgpu"
    Screen         0
    Option         "DRI"                    "3"
    Option         "TearFree"               "True"
    Option         "Monitor-HDMI-A-1"       "monitor-hisense"
EndSection

Section "Monitor"
    Identifier     "monitor-hisense"
    VendorName     "Hisense"
    ModelName      "43A7300F"
    Option         "Primary"                "true"
    Option         "PreferredMode"          "3840x2160_60"
EndSection

Section "Screen"
    Identifier     "screen-hisense"
    Device         "amdgpu"
    Monitor        "monitor-hisense"
    #Monitor       "monitor-lg"
EndSection

Section "ServerLayout"
  Identifier       "Main"
  Option           "DefaultServerLayout"
  Screen           0                     "screen-hisense"
EndSection
