Section "Monitor"
    Identifier     "monitor-hisense"
    VendorName     "Hisense"
    ModelName      "43A7300F"
    Option         "Primary"             "true"
    Option         "PreferredMode"       "3840x2160"
EndSection

Section "Monitor"
    Identifier     "monitor-avr-denon-1311"
    VendorName     "denon"
    ModelName      "1311"
    Option         "Primary"             "false"
    Option         "RightOf"             "DisplayPort-1"
    Option         "PreferredMode"       "640x480"
EndSection

Section "Screen"
    Identifier     "screen-hisense"
    Device         "gpu0"
    Monitor        "monitor-hisense"
EndSection

Section "Screen"
    Identifier     "screen-avr-denon-1311"
    Device         "gpu0"
    Monitor        "monitor-avr-denon-1311"
EndSection

Section "Device"
    Identifier     "gpu0"
    BusID          "PCI:9:0:0"
    Driver         "amdgpu"
    Screen         0
    Option         "DRI"                 "3"
    Option         "TearFree"            "True"
    Option         "VariableRefresh"   "false"
    Option         "Monitor-DisplayPort-1" "monitor-hisense"
    Option         "Monitor-HDMI-A-0"    "monitor-avr-denon-1311"
EndSection

Section "ServerLayout"
    Identifier     "Main"
    Option         "DefaultServerLayout"
    Screen         0                     "screen-hisense"
    Option         "BlankTime"           "30"
    Option         "StandbyTime"         "200"
    Option         "SuspendTime"         "2000"
    Option         "OffTime"             "3000"
EndSection

Section "ServerFlags"
    Option "NoPM" "true"
EndSection
