Section "Device"
	Identifier  "IntelVideo"
	Option      "AccelMethod"        "glamor"
	Option      "DRI"                "3"
	Driver      "modesetting"
EndSection

Section "Monitor"
	Identifier  "HDMI-2"
	Option      "RightOf"            "HDMI-1"
EndSection

Section "Monitor"
	Identifier  "HDMI-1"
	Option      "Primary"            "true"
EndSection

Section "Screen"
	Identifier  "L-Primary"
	Monitor	    "HDMI-1"
	Device	    "IntelVideo"
EndSection

Section "Screen"
	Identifier  "R-Secondary"
	Monitor	    "HDMI-2"
	Device	    "IntelVideo"
EndSection


Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us,bg"
        Option "XkbModel" "pc104"
        Option "XkbVariant" ",phonetic"
        Option "XkbOptions" "grp:ctrls_toggle"
EndSection
