Section "Device"
	Identifier  "Graphics"
	Option      "AccelMethod"	"sna"
	Option      "DRI"		"3"
	Driver      "modesetting"
	Option      "TearFree" "true"
EndSection

Section "Monitor"
	Identifier    "<default monitor>"
	Modeline      "1920x1080"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
	Option        "PreferredMode" "1920x1080"
EndSection

Section "Monitor"
    Identifier     "HDMI-1"
    VendorName     "Dell"
    ModelName      "U2713HM"
    Modeline   "2560x1440_50.00_rb" 200.25 2560 2608 2640 2720 1440 1443 1448 1474 +hsync -vsync
    Option "ModeValidation" "NoDFPNativeResolutionCheck"
EndSection

Section "Screen"
	Identifier    "Default Screen"
	Monitor	      "<default monitor>"
	Device	      "Graphics"
EndSection

