Section "Device"
	Identifier    "intel"
	BusID         "PCI:0:2:0"
	Driver        "modesetting"
	Screen	      0
	Option        "AccelMethod"	"sna"
	Option        "DRI"		"3"
	Option        "TearFree" "true"
	Option        "Monitor-eDP-1" "monitor-eDP-1"
	Option 	      "Monitor-HDMI-1" "monitor-HDMI-1"
	Option        "Monitor-DP-2" "monitor-DP-2"
	Option        "TripleBuffer" "true"
EndSection


Section "Monitor"
	Identifier    "monitor-eDP-1"
	VendorName    "integrated"
	Modeline      "1920x1080"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
	Option        "PreferredMode" "1920x1080"
	Option 	      "Primary" "true"
	Option        "Position" "640 1440"
EndSection
Section "Monitor"
        Identifier     "monitor-HDMI-1"
        VendorName     "Dell"
        ModelName      "U2713HM"
        Modeline       "2560x1440_50.00_rb" 200.25 2560 2608 2640 2720 1440 1443 1448 1474 +hsync -vsync
        Option         "ModeValidation" "NoDFPNativeResolutionCheck"
	Option         "PreferredMode" "2560x1440_50.00_rb"
        Option         "Above" "monitor-eDP-1"
	Option         "LeftOf" "monitor-DP-2"
	Option        "Position" "0 0"
EndSection
Section "Monitor"
	Identifier    "monitor-DP-2"
	VendorName    "asus"
	Option        "PreferredMode" "1920x1080"
	Option        "RightOf" "monitor-eDP-1"
	Option        "Rotate" "left"
	Option        "Position" "2560 0"
EndSection


Section "Screen"
	Identifier    "screen-eDP-1"
	Monitor	      "monitor-eDP-1"
	Device	      "intel"
EndSection
Section "Screen"
	Identifier    "screen-HDMI-1"
	Monitor	      "monitor-HDMI-1"
	Device	      "intel"
EndSection
Section "Screen"
	Identifier    "screen-DP-2"
	Monitor	      "monitor-DP-2"
	Device	      "intel"
EndSection

Section "ServerLayout"
  Identifier          "Main"
  Screen              0 "screen-eDP-1"
  Screen              1 "screen-HDMI-1"
  Screen              2 "screen-DP-2"
EndSection
