(global-set-key (kbd "<f5> n") 'indium-run-node)
;(global-set-key (kbd "[home]")     'beginning-of-line-text)
(global-set-key (kbd "<home>") 'beginning-of-line-text)

(defun duplicate-line()
  (interactive)
  (move-beginning-of-line 1)
  (kill-line)
  (yank)
  (open-line 1)
  (next-line 1)
  (yank)
)

(global-set-key (kbd "C-d") 'duplicate-line)