pcm.primary {
        type hw                # Kernel PCM
        card 0                 # Card name or number
        device 0               # Device number (default 0)     
        subdevice 0            # Subdevice number, -1 first available (default -1)
        #mmap_emulation BOOL   # enable mmap emulation for ro/wo devices
}

pcm.btr3 {
        type hw                # Kernel PCM
        card 1                 # Card name or number
        device 0               # Device number (default 0)     
        subdevice 0            # Subdevice number, -1 first available (default -1)
        #mmap_emulation BOOL   # enable mmap emulation for ro/wo devices
}