monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "bluez_output.BC_87_FA_5B_1D_94"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1070
        priority.driver  = 1070
      }
    }
  }
]
