monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "bluez_output.40_ED_98_19_9C_2C.1"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1070
        priority.driver  = 1070
      }
    }
  }
]
