monitor.alsa.rules = [
  {
    matches = [
      { media.class = "Audio/Sink", alsa.name = "DENON-AVAMP" }
    ]
    actions = {
      update-props = {
        priority.session = 2000
      }
    }
  }
]
