Section "Device"
	Identifier  "radeon"
	Option      "AccelMethod"	"glamor"
	Option      "DRI"		"3"
	Driver      "radeon"
	Option      "TearFree"          "True"
	Option      "ColorTiling"       "on"
	Option      "ColorTiling2D"     "on"
EndSection

Section "Device"
	Identifier  "amdgpu"
	Option      "DRI"		"3"
	Driver      "amdgpu"
	Option      "TearFree"          "True"
	Option	    "Monitor-DVI-D-0" 	"Dell"
EndSection

Section "Device"
	Identifier  "intelModesetting"
	Option      "AccelMethod"       "glamor"
	Option      "DRI"               "3"
	Driver      "modesetting"
EndSection

Section "Monitor"
    Identifier     "Dell"
    VendorName     "Dell"
    ModelName      "U2713HM"

    #Modeline "2560x1440_40.00"  201.00  2560 2720 2984 3408  1440 1443 1448 1476 +hsync +vsync
    #Option "PreferredMode" "2560x1440_40.00"
    Option "PreferredMode" "2560x1440"
    Option      "Primary"            "true"
EndSection

#Section "Monitor"
#	Identifier  "Asus"
#	Option      "LeftOf"            "DVI-D-0"
#	Option "PreferredMode" "1920x1080"
#	Option "Primary" "false"
#EndSection

Section "Screen"
    Identifier     "Dell-U2713HM"
    Device         "amdgpu"
    Monitor        "Dell"
EndSection
#Section "Screen"
#	Identifier  "L-Secondary"
#	Monitor	    "Asus"
#	Device	    "amdgpu"
#EndSection
